spring:
  data:
    mongodb:
      uri: mongodb+srv://willneimann:pkskok12@mongbitdb.unaoa4m.mongodb.net/mongbitdb?retryWrites=true&w=majority

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3245a5f9cb8303814aadbe1eb65b2e73 # REST API KEY
            client-secret: 7FtHbXlW6FIoWjDb2hMUfNCqaExv3Opv # Client Secret
            redirect-uri: http://localhost:8080/login/oauth2/kakao/code # Redirect URI
            authorization-grant-type: authorization_code
            scope:
            client-name: Kakao
            client-authentication-method: post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.MongMoong.MongBitProject: TRACE
  file:
    name: app.log
# TRACE : 가장 상세한 로그 메세지. 개발 시 디버깅 용도로 사용.
# DEBUG : 시스템의 동작 상황을 상세히 알려주는 로그 메세지. 일반적으로 개발 단계에서 사용.
# INFO : 일반적인 정보를 나타내는 로그 메세지 프로덕션 환경에서도 유용한 정보를 제공.
# WARN : 가능한 문제를 나타내는 로그 메세지. 당장 시스템에 치명적인 영향은 없지만, 주의가 필요한 상황을 나타냄.
# ERROR : 치명적인 문제를 나타내는 로그 메세지. 시스템 동작에 문제가 있을 경우 표시.

admin:
  token: "AAABnv/xRVklrnYxKZ0aHgTBcXukeZygoC"
jwt:
  secret: "5v8y/B?E(H+MbPeShVmYq3t6w9z$C&F)"
kakao:
  oauth:
    url: "https://kauth.kakao.com/oauth/authorize?client_id=3245a5f9cb8303814aadbe1eb65b2e73&redirect_uri=https://mongbit.vercel.app/login/oauth2/kakao/code&response_type=code"
    client-id: "3245a5f9cb8303814aadbe1eb65b2e73"
imgbb:
  key: 8157b37797b76c11b2c257b37b1a7080

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
# REST API KEY
# 3245a5f9cb8303814aadbe1eb65b2e73

# Redirect URI
# http://localhost:8080/login/oauth2/kakao/code

# Client Secret
# 7FtHbXlW6FIoWjDb2hMUfNCqaExv3Opv

# 로컬 테스트용 url
# https://kauth.kakao.com/oauth/authorize?client_id=3245a5f9cb8303814aadbe1eb65b2e73&redirect_uri=http://localhost:8080/login/oauth2/kakao/code&response_type=code
# 배포 테스트용 url
# https://kauth.kakao.com/oauth/authorize?client_id=3245a5f9cb8303814aadbe1eb65b2e73&redirect_uri=https://mongbit-willneiman.koyeb.app/login/oauth2/kakao/code&response_type=code